### ISSUE TITLE
Incorrect instructions in README

### ISSUE THREAD

**Issue by leoc-22** [localstack/localstack-pro-samples#224]
In https://github.com/localstack/localstack-pro-samples/blob/master/lambda-hot-reloading/typescript/README.md?plain=1#L72, the command should be 
```
awslocal lambda invoke \
    --function-name hello-world \
    --cli-binary-format raw-in-base64-out \
    --payload '{"action": "test"}' output.txt
```

Without specifying --cli-binary-format option, it will return `Invalid base64: "{"action": "test"}"`

**Comment by joe4dev** [comment]
Thank you for sharing this feedback 🙏 

The command depends on the version of the AWS CLI (v1 vs. v2). We updated all documentation using inline payloads with a tabpane offering commands for both versions:
<img width="714" alt="Screenshot 2023-09-17 at 15 54 41" src="https://github.com/localstack/localstack-pro-samples/assets/8161292/61886cf3-f2a9-4f44-8803-b54742e60e40">
